name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

        - name: Lint
          run: make fmt

        - name: Tests
          run: make tests

        - name: Install EB CLI
          run: pip install awsebcli

        - name: Deploy to Elastic Beanstalk
          run: |
            eb deploy fastapi-eb-template
