name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

        - uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: Install AWS EB CLI
          run: |
            pip install --upgrade awsebcli

        - name: Deploy to Elastic Beanstalk
          run: |
            eb deploy fastapi-eb-template
