name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: make install

        - name: Lint
          run: make fmt

        - name: Tests
          run: make tests

        - name: Install EB CLI
          run: |
            pip install --upgrade pip
            pip install awsebcli

        - name: Use stack
          run: |
            eb use fastapi-eb-template
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: Deploy to Elastic Beanstalk
          run: |
            eb deploy fastapi-eb-template
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
